### ISSUE TITLE
Internal crash `invalid channel index` inside `decode` function

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#122]
This code
https://github.com/qarmin/audio_checker/blob/master/src/lib.rs

cause when opening example file, this internal crash
```
thread '<unnamed>' panicked at 'invalid channel index', /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/symphonia-core-0.5.0/src/audio.rs:577:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:616:12
   1: <symphonia_core::audio::AudioBuffer<S> as symphonia_core::audio::Signal<S>>::chan_mut
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/symphonia-core-0.5.0/src/audio.rs:577:9
   2: symphonia_bundle_mp3::layer3::decode_frame
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/symphonia-bundle-mp3-0.5.0/src/layer3/mod.rs:346:34
   3: symphonia_bundle_mp3::decoder::Mp3Decoder::decode_inner
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/symphonia-bundle-mp3-0.5.0/src/decoder.rs:43:17
   4: <symphonia_bundle_mp3::decoder::Mp3Decoder as symphonia_core::codecs::Decoder>::decode
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/symphonia-bundle-mp3-0.5.0/src/decoder.rs:82:25
   5: audio_checker::parse_audio_file
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/audio_checker-0.1.0/src/lib.rs:59:9
   6: czkawka_core::broken_files::BrokenFiles::look_for_broken_files::{{closure}}::{{closure}}
             at ./Projekty/Rust/czkawka/czkawka_core/src/broken_files.rs:476:43
   7: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
   8: __rust_try
   9: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  10: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  11: czkawka_core::broken_files::BrokenFiles::look_for_broken_files::{{closure}}
             at ./Projekty/Rust/czkawka/czkawka_core/src/broken_files.rs:475:46
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:247:13
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:280:13
  14: core::option::Option<T>::map
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:906:29
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  16: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/take_while.rs:46:21
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  18: rayon::iter::plumbing::Folder::consume_iter
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:178:21
  19: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/while_some.rs:139:21
  20: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/map.rs:248:21
  21: rayon::iter::plumbing::Producer::fold_with
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:110:9
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:438:13
  23: rayon::iter::plumbing::bridge_producer_consumer
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:397:12
  24: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:373:13
  25: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/vec.rs:147:13
  26: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/vec.rs:83:9
  27: rayon::iter::plumbing::bridge
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/plumbing/mod.rs:357:12
  28: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/vec.rs:58:9
  29: <rayon::collections::btree_map::IntoIter<K,V> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/delegate.rs:30:17
  30: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/map.rs:49:9
  31: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/while_some.rs:44:9
  32: <rayon::iter::filter::Filter<I,P> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/filter.rs:46:9
  33: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/map.rs:49:9
  34: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/extend.rs:576:28
  35: rayon::iter::from_par_iter::collect_extended
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/from_par_iter.rs:17:5
  36: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/from_par_iter.rs:30:9
  37: rayon::iter::ParallelIterator::collect
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.2/src/iter/mod.rs:2046:9
  38: czkawka_core::broken_files::BrokenFiles::look_for_broken_files
             at ./Projekty/Rust/czkawka/czkawka_core/src/broken_files.rs:422:50
  39: czkawka_core::broken_files::BrokenFiles::find_broken_files
             at ./Projekty/Rust/czkawka/czkawka_core/src/broken_files.rs:110:13
  40: czkawka_gui::connect_things::connect_button_search::connect_button_search::{{closure}}::{{closure}}
             at ./Projekty/Rust/czkawka/czkawka_gui/src/connect_things/connect_button_search.rs:484:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Example file - [Robin Cook - Pandemia (54)4.mp3.zip](https://github.com/pdeljanov/Symphonia/files/8645857/Robin.Cook.-.Pandemia.54.4.mp3.zip)

**Comment by pdeljanov** [comment]
Hi @qarmin,

This file seems to play with the latest code in master. Could you confirm?

**Comment by qarmin** [comment]
Yes, crash is fixed

**Comment by torokati44** [comment]
FYI panic also happened when playing z0r.de/5183 with Ruffle using its optional Symphonia decoder. Here is the audio exported from it: [z0r-de_5183.zip](https://github.com/pdeljanov/Symphonia/files/8661846/z0r-de_5183.zip)

And that is now also fixed.
