### ISSUE TITLE
Crash due unimplemented `first-sample-flags-present`

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#127]
When opening file with this code - https://github.com/qarmin/audio_checker/blob/master/src/lib.rs

I got this crash
```
thread '<unnamed>' panicked at 'not yet implemented: support truns with first-sample-flags-present', /home/rafal/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/8f4aaed/symphonia-format-isomp4/src/atoms/trun.rs:96:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: <symphonia_format_isomp4::atoms::trun::TrunAtom as symphonia_format_isomp4::atoms::Atom>::read
   3: <symphonia_format_isomp4::atoms::traf::TrafAtom as symphonia_format_isomp4::atoms::Atom>::read
   4: <symphonia_format_isomp4::atoms::moof::MoofAtom as symphonia_format_isomp4::atoms::Atom>::read
   5: symphonia_format_isomp4::demuxer::IsoMp4Reader::try_read_more_segments
   6: <symphonia_format_isomp4::demuxer::IsoMp4Reader as symphonia_core::formats::FormatReader>::next_packet
   7: crates_tester::symphonia::parse_audio_file
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   9: rayon::iter::plumbing::Producer::fold_with
  10: rayon_core::registry::in_worker
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
  14: rayon_core::job::StackJob<L,F,R>::run_inline
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: rayon_core::job::StackJob<L,F,R>::run_inline
  18: rayon_core::registry::in_worker
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: <rayon_core::job
::StackJob<L,F,R> as rayon_core::job::Job>::execute
  23: rayon_core::registry::WorkerThread::wait_until_cold
  24: rayon_core::registry::ThreadBuilder::run
```

[QgRh0uNIsrOSrj3OpIBkihCM4m5yYXTy.zip](https://github.com/pdeljanov/Symphonia/files/8693210/QgRh0uNIsrOSrj3OpIBkihCM4m5yYXTy.zip)

**Comment by pdeljanov** [comment]
This should be fixed now. Cheers!
