### ISSUE TITLE
Crash when checking file

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#128]
Opening 
[3iqq1c9t2clr909s.zip](https://github.com/pdeljanov/Symphonia/files/8693215/3iqq1c9t2clr909s.zip)

with https://github.com/qarmin/audio_checker/blob/master/src/lib.rs crashes with this backtrace 
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rafal/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/8f4aaed/symphonia-format-isomp4/src/atoms/meta.rs:63:50
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: <symphonia_format_isomp4::atoms::meta::MetaAtom as symphonia_format_isomp4::atoms::Atom>::read
   4: <symphonia_format_isomp4::demuxer::IsoMp4Reader as symphonia_core::formats::FormatReader>::try_new
   5: core::ops::function::FnOnce::call_once
   6: symphonia_core::probe::Probe::format
   7: crates_tester::symphonia::parse_audio_file
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   9: rayon::iter::plumbing::Producer::fold_with
  10: rayon_core::registry::in_worker
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  13: rayon_core::registry::WorkerThread::wait_until_cold
  14: rayon_core::registry::in_worker
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: rayon_core::job::StackJob<L,F,R>::run_inline
  17: rayon_core::registry::in_worker
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  20: rayon_core::registry::WorkerThread::wait_until_cold
  21: rayon_core::registry::ThreadBuilder::run
```

**Comment by pdeljanov** [comment]
Fixed!
