### ISSUE TITLE
Out of bound crash when checking file(probably invalid)

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#129]
https://github.com/qarmin/audio_checker/blob/master/src/lib.rs
with file 

[EgpPus2Z.zip](https://github.com/pdeljanov/Symphonia/files/8693231/EgpPus2Z.zip)
caused this crash
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 41 but the index is 41', /home/rafal/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/8f4aaed/symphonia-codec-aac/src/aac.rs:809:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
   3: symphonia_codec_aac::aac::Ics::decode_ics
   4: <symphonia_codec_aac::aac::AacDecoder as symphonia_core::codecs::Decoder>::decode
   5: crates_tester::symphonia::parse_audio_file
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   7: rayon::iter::plumbing::Producer::fold_with
   8: rayon_core::job::StackJob<L,F,R>::run_inline
   9: rayon_core::registry::in_worker
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: rayon_core::job::StackJob<L,F,R>::run_inline
  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
  14: rayon_core::job::StackJob<L,F,R>::run_inline
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: rayon_core::registry::in_worker
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: rayon_core::registry::in_worker
  20: rayon::iter::plumbing::bridge_producer_consumer::helper
  21: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  22: rayon_core::registry::WorkerThread::wait_until_cold
  23: rayon_core::registry::in_worker
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: rayon_core::registry::in_worker
  26: rayon::iter::plumbing::bridge_producer_consumer::helper
  27: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  28: rayon_core::registry::WorkerThread::wait_until_cold
  29: rayon_core::registry::ThreadBuilder::run
```

**Comment by pdeljanov** [comment]
This specific case is fixed in 2a73af4083aaa8a4400659cd379e42dda0fd52af.

The AAC decoder will need some fuzzing time to prevent more issues like this.
