### ISSUE TITLE
Panic with invalid file

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#201]
[{9eed17b5-905c-4383-9b66-30b64c49aceb}.mp3.zip](https://github.com/pdeljanov/Symphonia/files/11172299/9eed17b5-905c-4383-9b66-30b64c49aceb.mp3.zip)

crashes:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Tracks`,
 right: `Info`: EBML element type must be checked before calling this function', /home/rafal/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/b4ef823/symphonia-format-mkv/src/ebml.rs:344:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: symphonia_format_mkv::ebml::ElementIterator<R>::read_element_data
   5: symphonia_format_mkv::ebml::ElementIterator<R>::read_element
   6: <symphonia_format_mkv::demuxer::MkvReader as symphonia_core::formats::FormatReader>::try_new
   7: core::ops::function::FnOnce::call_once
   8: symphonia_core::probe::Probe::format
   9: symphonia::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pdeljanov** [comment]
Apologies this took so long. This is now fixed.
