### ISSUE TITLE
verify_timebase test failing on i386 architecture

### ISSUE THREAD

**Issue by tenzap** [pdeljanov/Symphonia#254]
While attempting to build symphonia-core on Debian on i386 architecture we are facing this error.
There is no such error on the other architectures (the test passes).

A 2nd run leads to the same problem.

Command:
`RUST_BACKTRACE=1 /usr/bin/cargo -Zavoid-dev-deps test --verbose --verbose -j6 --target i686-unknown-linux-gnu --all`

Full log: https://buildd.debian.org/status/fetch.php?pkg=rust-symphonia-core&arch=i386&ver=0.5.2-1%2Bb1&stamp=1705866665&raw=1

```
---- units::tests::verify_timebase stdout ----
thread 'units::tests::verify_timebase' panicked at 'assertion failed: `(left == right)`
  left: `4503599627370496`,
 right: `4503599627370497`', src/units.rs:257:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:228:5
   4: symphonia_core::units::tests::verify_timebase
             at /usr/share/cargo/registry/symphonia-core-0.5.2/src/units.rs:257:9
   5: symphonia_core::units::tests::verify_timebase::{{closure}}
             at /usr/share/cargo/registry/symphonia-core-0.5.2/src/units.rs:236:26
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    units::tests::verify_timebase
```

```

---- units::tests::verify_timebase stdout ----
thread 'units::tests::verify_timebase' panicked at 'assertion failed: `(left == right)`
  left: `4503599627370496`,
 right: `4503599627370497`', src/units.rs:257:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:228:5
   4: symphonia_core::units::tests::verify_timebase
             at /usr/share/cargo/registry/symphonia-core-0.5.2/src/units.rs:257:9
   5: symphonia_core::units::tests::verify_timebase::{{closure}}
             at /usr/share/cargo/registry/symphonia-core-0.5.2/src/units.rs:236:26
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    units::tests::verify_timebase
```

**Comment by pdeljanov** [comment]
Hmm, I wasn't able to reproduce this using a virtual machine and a Debian i386 image. I'm running on an Intel 4790k.

However, I was using the official Rust build. @dedobbin maybe you could try reproducing on your end?

**Comment by pdeljanov** [comment]
Oh I see. I wouldn't be surprised if the issue is related to https://github.com/rust-lang/rust/issues/114479. I see that some tests are also disabled in [this](https://salsa.debian.org/rust-team/rust/-/blob/debian/sid/debian/patches/u-disable-fp-precision-test-on-i386.patch?ref_type=heads) patch for similar reasons presumably.

I tried to emulate by running with `RUSTFLAGS="-C target-cpu=pentiumpro" cargo +1.70.0-i686-unknown-linux-gnu tests`, but still no repro on my end.

**Comment by pdeljanov** [comment]
This issue has gone quiet. However, I expect v0.6.0 to have resolved it since the implementation is more straightforward.

**Comment by tenzap** [comment]
I just tested with 0.6.0 and indeed, the tests now pass on i386. Thanks
